// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_glCW9zpMrEf1VooZ3wvMmZO_UEuPuxs',
    appId: '1:1028425122510:web:02236cda6d15f9cfae069f',
    messagingSenderId: '1028425122510',
    projectId: 'fluttersfc-a94dd',
    authDomain: 'fluttersfc-a94dd.firebaseapp.com',
    storageBucket: 'fluttersfc-a94dd.firebasestorage.app',
    measurementId: 'G-S73WV3YS8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqq76-BdZFdIkns71m1y5AheTNKcQGvFU',
    appId: '1:1028425122510:android:122f08a87684adfcae069f',
    messagingSenderId: '1028425122510',
    projectId: 'fluttersfc-a94dd',
    storageBucket: 'fluttersfc-a94dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRu4QtKrZWWnRm_NfCZGJTSvdnp70bDG4',
    appId: '1:1028425122510:ios:f45be09beae9b9bdae069f',
    messagingSenderId: '1028425122510',
    projectId: 'fluttersfc-a94dd',
    storageBucket: 'fluttersfc-a94dd.firebasestorage.app',
    iosClientId: '1028425122510-j9ugk3a100sqrs9cnebjp7vv36l72o6e.apps.googleusercontent.com',
    iosBundleId: 'com.example.pennypalAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRu4QtKrZWWnRm_NfCZGJTSvdnp70bDG4',
    appId: '1:1028425122510:ios:f45be09beae9b9bdae069f',
    messagingSenderId: '1028425122510',
    projectId: 'fluttersfc-a94dd',
    storageBucket: 'fluttersfc-a94dd.firebasestorage.app',
    iosClientId: '1028425122510-j9ugk3a100sqrs9cnebjp7vv36l72o6e.apps.googleusercontent.com',
    iosBundleId: 'com.example.pennypalAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_glCW9zpMrEf1VooZ3wvMmZO_UEuPuxs',
    appId: '1:1028425122510:web:a6e74182c38ef387ae069f',
    messagingSenderId: '1028425122510',
    projectId: 'fluttersfc-a94dd',
    authDomain: 'fluttersfc-a94dd.firebaseapp.com',
    storageBucket: 'fluttersfc-a94dd.firebasestorage.app',
    measurementId: 'G-MGNCSZZ47L',
  );
}
